#
# User data
#

# user_name: john

# user_full_name: John Doe

# user_github_username: johndoe
# user_github_email: johndoe@email.com

# user_github_gnupg_sign: false
# user_gnupg_key_id: '0x9999999999999999'
