- name: Set timezone to {{ system_timezone }}
  become: yes
  timezone:
    name: '{{ system_timezone }}'

- name: Ensure the locale {{ system_locale }} exists
  become: yes
  locale_gen:
    name: '{{ system_locale }}'

- name: Set maximum size for persistent journal
  become: yes
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: 100M

- name: Restart systemd-journald service
  become: yes
  systemd:
    name: systemd-journald.service
    state: restarted

# https://avahi.org/
- name: Set up avahi local hostname resolution
  become: yes
  lineinfile:
    path: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'

- name: Do not allow NetworkManager to manage resolv.conf
  become: yes
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: 0644
    section: main
    option: rc-manager
    value: unmanaged

- name: Set DNS resolvers
  become: yes
  copy:
    content: '{{ system_resolvconf }}'
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Create systemd-resolvers conf.d dir
  become: yes
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set systemd-resolved configuration
  become: yes
  template:
    src: etc/systemd/resolved.conf.d/dns_over_tls.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_over_tls.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart systemd-resolved

- name: Enable services
  become: yes
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
    - avahi-daemon
    - NetworkManager
    - systemd-resolved
