---

- name: Ensure {{ user_name }} user exists
  become: true
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups:
      - root
      - wheel
      - users
    append: true
    shell: '/usr/bin/zsh'

- name: Ensure the ~/.ssh directory exists for {{ user_name }}
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/.ssh'
    state: directory
    owner: '{{ user_name }}'
    group: users
    mode: '0700'

- name: Add extra home directories
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: users
    mode: '0755'
  loop: '{{ user_extra_home_dirs }}'

- name: Add home .config directory
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: users
    mode: '0755'
  loop:
    - .config
    - .bin

- name: Ensure bash directories exist for {{ user_name }}
  become_user: '{{ user_name }}'
  ansible.builtin.file:
    path: '/home/{{ user_name }}/{{ item }}'
    state: directory
    owner: '{{ user_name }}'
    group: users
    mode: '0755'
  loop:
    - .bash_aliases.d
    - .bash_env.d
    - .bash_completions.d

- name: Add user configuration files
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/{{ item }}'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: users
    mode: '0644'
  loop:
    - .bash_logout
    - .bash_profile
    - .bashrc
    - Makefile

- name: Add user .ssh configuration file
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/.ssh/config'
    dest: '/home/{{ user_name }}/.ssh/config'
    owner: '{{ user_name }}'
    group: users
    mode: '0644'

- name: Add user Backup scripts folder
  become_user: '{{ user_name }}'
  ansible.builtin.copy:
    src: 'home/.scripts'
    dest: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: users
    mode: '0755'
