---

- name: Install packages
  become: true
  community.general.pacman:
    state: present
    name:
      - android-tools
      - ansible-lint
      - bridge-utils
      - dnsmasq
      - dnsutils
      - docker-compose
      - emacs
      - github-cli
      - go
      - grype
      - inetutils
      - jq
      - jdk11-openjdk
      - kubectl
      - kustomize
      - leiningen
      - libusb-compat
      - maven
      - net-tools
      - ngrep
      - openbsd-netcat
      - packer
      - podman
      - podman-docker
      - python2
      - python-pipenv
      - python-poetry
      - python-wheel
      - twine
      - sops
      - starship
      - terraform
      - tmux
      - traceroute
      - vault
      - wireshark-qt
      - yamllint

- name: Install AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - aws-cli-v2-bin
      - authy
      - brave-bin
      - gdrive
      - google-cloud-sdk
      - pip-tools
      - pyenv-virtualenv
      - slack-desktop
      - terraform-docs
      - tflint-bin
      - tfsec-bin
      - velero-bin
      - visual-studio-code-bin
      - woeusb-ng
      - zoom
      - zplug
