---

- name: Archlinux-specific setup
  import_tasks: archlinux.yml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: System dev configuration
  import_tasks: system.yml

- name: User dev configuration
  import_tasks: user.yml
